version: '3'

services:
  admin:
    container_name: nekotoko-admin
    build:
      context: ../..
      dockerfile: apps/admin/Dockerfile
      target: development
    command: yarn serve admin
    ports:
      - '${ADMIN_PORT}:3000'
    volumes:
      - ../..:/app
      - ../../node_modules:/app/node_modules
    env_file:
      - ../../apps/admin/.env

  pos:
    container_name: nekotoko-pos
    build:
      context: ../..
      dockerfile: apps/pos/Dockerfile
      target: development
    command: yarn serve pos
    ports:
      - '${POS_PORT}:3001'
    volumes:
      - ../..:/app
      - ../../node_modules:/app/node_modules
    env_file:
      - ../../apps/pos/.env

networks:
  default:
    name: nekotoko-global
    external: true
