version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-test-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn
          with-cache: false
      - run:
          command: yarn affected:deploy --base=<< pipeline.git.base_revision >> --head=HEAD
          name: build affected

workflows:
  build-test-and-deploy:
    jobs:
      - build-test-and-deploy:
          filters:
            branches:
              only:
                - main
